apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: your-docker-repo/store
      context: ../store
      jib: {}
    - image: your-docker-repo/invoice
      context: ../invoice
      jib: {}
    - image: your-docker-repo/product
      context: ../product
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
